name: yetiorm
description: A sample package application.
version: 0.0.1
repository: https://github.com/yetiOSS/yetiorm

environment:
  sdk: ^3.7.0

dependencies:
  meta: ^1.16.0
  mysql1: ^0.20.0
  path: ^1.8.0
  postgres: ^3.5.4
  reflectable: ^4.0.12
  sqlite3: ^2.7.5

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
